name: Build
on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    name: Build jar
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  test:
    name: Unit test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests
